#nombre del microservicio -> para posteriormente llamarlo por su nombre(en eureka, load balancer, etc) y no por el url del recurso u otro.
spring:
  application:
    name: service-products

server:
  port: 8001

eureka:
  client:
    service-url:
      #      Always enter the path where the eureka server is located.
      defaultZone: http://localhost:8761/eureka